# Graduate Rotational Internship Program @The Sparks Foundation
## **Author** : **Mahadevan A Nair**
### **Task 1** : Object Detection

* *Description : Implement an object detector which identifies the classes of the objects in an image or video*

In [1]:
#importing opencv and numpy modules
import cv2
import numpy as np

In [2]:
#declaring threshold
whT = 320

In [3]:
#loading coco names containing the objects
className = []
with open('coco.names', 'rt') as f:
    classNames = f.read().splitlines()

In [4]:
#loading the yolo weights and configuration files
model_cfg = 'yolov3.cfg'
model_weights = 'yolov3.weights'

In [5]:
#setting opencv as backend and target as cpu
net = cv2.dnn.readNet(model_cfg, model_weights)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)

In [6]:
#function for object detection 
def findObjects(output, img):
    hT, wT, cT = img.shape
    boxes = []
    class_ids = []
    confidences = []

    for output in outputs:
        for detection in output:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]
            if confidence > 0.5:
                w = int(detection[2]*wT)
                h = int(detection[3]*hT)
                x = int((detection[0]*wT)-w/2)
                y = int((detection[1]*hT)-h/2)
                boxes.append([x, y, w, h])
                class_ids.append(class_id)
                confidences.append(float(confidence))

    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, nms_threshold=0.3)
    print(indexes)
    
    #setting the color and font to be displayed
    font = cv2.FONT_HERSHEY_SIMPLEX
    colors = np.random.uniform(0, 255, size=(len(boxes), 3))
    
    for i in indexes.flatten():
        x, y, w, h = boxes[i]
        label = str(classNames[class_ids[i]])
        confidence = str(round(confidences[i],2))
        color = colors[i]
        cv2.rectangle(img, (x, y), (x+w, y+h), color, 2)
        cv2.putText(img, label + " " + confidence, (x, y+20), font, 0.6, (255, 0, 255), 2)

In [7]:
#opencv code for loading video
cap = cv2.VideoCapture('video.mp4')
while True :
    success, img = cap.read()
    blob = cv2.dnn.blobFromImage(img, 1/255, (whT, whT), [0, 0, 0], 1, crop= False)
    net.setInput(blob)

    layerNames = net.getLayerNames()
    out_Names = [layerNames[i[0]-1] for i in net.getUnconnectedOutLayers()]
    print(out_Names)
    
    outputs = net.forward(out_Names)
    findObjects(outputs, img)

    cv2.imshow('image', img)
    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()

['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 1]
 [ 8]
 [10]
 [17]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 1]
 [ 8]
 [10]
 [17]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 1]
 [ 8]
 [10]
 [17]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 1]
 [ 8]
 [17]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 1]
 [ 8]
 [17]
 [10]
 [18]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 2]
 [ 9]
 [18]
 [11]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 5]
 [17]
 [11]
 [18]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 5]
 [17]
 [11]
 [18]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 5]
 [17]
 [11]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 1]
 [ 4]
 [16]
 [17]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 5]
 [17]
 [11]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 2]
 [ 5]
 [17]
 [11]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 2]
 [ 5]
 [17]
 [11]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 2]
 [ 5]
 [17]
 [11]
 [19]]
['yolo_82', 'yol

[[ 4]
 [ 1]
 [ 6]
 [13]
 [17]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 6]
 [12]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 6]
 [12]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 6]
 [13]
 [17]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 6]
 [12]
 [16]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 7]
 [ 6]
 [12]
 [14]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 7]
 [ 6]
 [13]
 [15]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [13]
 [15]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [13]
 [15]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 7]
 [13]
 [15]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [12]
 [16]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 5]
 [ 6]
 [11]
 [14]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 7]
 [14]
 [16]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [13]
 [16]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [13]
 [17]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [14

[[ 5]
 [ 8]
 [ 7]
 [17]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 7]
 [15]
 [17]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 7]
 [17]
 [19]
 [16]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 5]
 [ 7]
 [ 2]
 [19]
 [21]
 [18]
 [11]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [16]
 [18]
 [15]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [16]
 [18]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 1]
 [17]
 [18]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 6]
 [ 7]
 [16]
 [18]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 5]
 [ 1]
 [ 7]
 [16]
 [11]
 [18]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 6]
 [ 9]
 [ 8]
 [18]
 [13]
 [20]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 2]
 [ 8]
 [17]
 [13]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 6]
 [ 2]
 [ 7]
 [16]
 [18]
 [12]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 6]
 [ 2]
 [ 7]
 [16]
 [12]
 [18]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 6]
 [ 8]
 [ 7]
 [16]
 [12]
 [18]]
['yolo_82', 'yolo_94', 'yolo_106'

[[14]
 [ 1]
 [ 6]
 [16]
 [21]
 [10]
 [23]]
['yolo_82', 'yolo_94', 'yolo_106']
[[13]
 [ 1]
 [ 4]
 [14]
 [ 8]
 [19]
 [21]]
['yolo_82', 'yolo_94', 'yolo_106']
[[13]
 [ 1]
 [ 4]
 [14]
 [ 8]
 [19]
 [21]]
['yolo_82', 'yolo_94', 'yolo_106']
[[15]
 [ 1]
 [ 6]
 [17]
 [21]
 [10]
 [23]]
['yolo_82', 'yolo_94', 'yolo_106']
[[12]
 [ 1]
 [ 4]
 [14]
 [ 7]
 [18]
 [20]]
['yolo_82', 'yolo_94', 'yolo_106']
[[12]
 [ 1]
 [ 4]
 [14]
 [ 7]
 [18]
 [20]]
['yolo_82', 'yolo_94', 'yolo_106']
[[14]
 [ 1]
 [ 5]
 [16]
 [19]
 [ 8]
 [21]]
['yolo_82', 'yolo_94', 'yolo_106']
[[11]
 [ 1]
 [ 4]
 [17]
 [12]
 [ 7]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[11]
 [ 1]
 [ 4]
 [17]
 [12]
 [ 7]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[11]
 [ 1]
 [ 4]
 [17]
 [ 7]
 [12]
 [19]]
['yolo_82', 'yolo_94', 'yolo_106']
[[10]
 [ 1]
 [ 4]
 [16]
 [ 7]
 [11]
 [18]]
['yolo_82', 'yolo_94', 'yolo_106']
[[12]
 [ 5]
 [ 1]
 [18]
 [ 9]
 [14]
 [20]]
['yolo_82', 'yolo_94', 'yolo_106']
[[12]
 [ 1]
 [ 4]
 [14]
 [19]
 [ 9]
 [21]]
['yolo_82', 'yolo_94'

AttributeError: 'tuple' object has no attribute 'flatten'

In [1]:
print("hello")

hello
